---
-  hosts: 172.31.44.8
   become: yes
   tasks:
    - name: install git
      apt:
        name: git
        state: present

    - name: install wget
      apt:
       name: wget
       stateee: present

    - name: i want to install tree
      apt:
       name: tree
       state: present
